PC/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()
 
app_name='Webpcx'

urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'Contacto$',views.Contacto, name='Contacto'),
    url(r'Servicios$',views.Servicios, name='Servicios'),
    url(r'Gracias$',views.Gracias, name='Gracias'),
    url(r'jovenes$',views.jovenes, name='jovenes'),
    url(r'nuevo$',views.nuevo, name='nuevo'),
    url(r'enviar$',views.enviar, name='enviar'),
    url(r'ingresar$',views.ingresar, name='ingresar'),
    url(r'Noticias$',views.Noticias, name='Noticias'),
    url(r'LogSec$',views.LogSec, name='LogSec'),    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pagina/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('PC/', include('PC.urls')),
    path('',views.home),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

PC/models.py
from django.db import models
# Create your models here.

class NuevaNot(models.Model):
    titulo = models.CharField(max_length=500)
    fecha = models.DateField()
    descripcion = models.CharField(max_length=500)
    link = models.CharField(max_length=500)
    imagen = models.ImageField(upload_to=(''))

    def __str__(self):
        return "{0} {1} {2} {3} {4}".format(self.titulo,self.fecha,self.descripcion,self.link,self.imagen)


class UserLog(models.Model):
    nombre = models.CharField(max_length=50)
    clave = models.CharField(max_length=12)

    def __str__(self):
        return "{0} {1}".format(self.nombre,self.clave)

PC/forms.py
from django import forms
from . import models
 

class NuevaNoti(forms.ModelForm):
    class Meta:
        model = models.NuevaNot
        fields = ['titulo','fecha','descripcion','link','imagen']

class LogU(forms.ModelForm):
    class Meta:
        model = models.UserLog
        fields = ['nombre','clave']

PC/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from .models import NuevaNot, UserLog
from .forms import NuevaNoti, LogU

# Create your views here.
def index(request):
    return render(request, 'index.html')

def Contacto(request):
    return render(request, 'Contacto.html')

def Servicios(request):
    return render(request, 'Servicios.html')

def Gracias(request):
    return render(request, 'Gracias.html')

def jovenes(request):
    return render(request, 'jovenes-intentaron-destruir-camara-de-seguridad-en-plaza-de-las-condes.html')

def nuevo(request):
    return render(request, 'nuevo-boton-de-emergencia.html')

def enviar(request):
    return render(request, 'enviar.php')

def ingresar(request):
    if request.method=='POST':
        form = NuevaNoti(request.POST,request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
        return redirect('Webpcx:Noticias')
    else:
        form=NuevaNoti()
    return render(request, 'ingresar.html', {'form':form})


def Noticias(request):
    Webpcx = NuevaNot.objects.all().order_by('-fecha','-id')
    return render(request, 'Noticias.html', {'list':Webpcx})

def LogSec(request):
    if request.method=='GET':
        form = LogU(request.GET)
        if form.is_valid():
            post.author = request.user
        return redirect('Webpcx.ingresar')
    else:
        form=LogU()
    return render(request,'LogSec.html',{'form':form})

pagina/views.py
from django.shortcuts import render

def home(request):
    return render(request,'index.html')

PC/templates/Contacto.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta name="description" content="">
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta property="og:title" content="Webpcx - Tecnologia en Evolucion" />
  <meta property="og:description" content="Camaras y Sistemas de seguirdad- Soporte y redes" />
  <meta property="og:image" content="http://webpcx.cl/img/webpcx_png.png" />
  <meta property="og:image:width" content="300" />
  <meta property="og:image:height" content="300" />      
  <meta property="og:url" content="http://www.webpcx.cl" />

  <title>Contacto</title>
  
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'animate-css/animate.min.css' %}">
  <link rel="stylesheet" href="{% static 'Morphext-2.4.4/morphext.css' %}">
  <link rel="stylesheet" href="{% static 'css/webpcx.css' %}">
</head>

<body>

<div class="header-contacto">
      <div class="fondo-header">
        <header >

        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#miNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'Webpcx:index' %}"><span class="logo-prim">Web</span><span class="logo-sec">Pcx</span></a>
            </div>
            <div class="collapse navbar-collapse" id="miNavbar">
              <ul class="nav navbar-nav navbar-right">
                <li class=""><a href="{% url 'Webpcx:index' %}">Inicio</a></li>
                <li class=""><a href="{% url 'Webpcx:Servicios' %}">Servicios</a></li>
                <li class="active"><a href="{% url 'Webpcx:Contacto' %}">Contacto</a></li>
                <li class=""><a href="{% url 'Webpcx:Noticias' %}">Noticias</a></li>
              </ul>
            </div>
          </div>
        </nav>
        </header>

<section id="introServicio">
    <div class="container-intro">
    <div class="">
      <div class="intro-logo wow fadeInDown">
        <img src="{% static 'img/webpcx_png.png' %}" width="950px" alt="logopcx">
      </div>
      <h1 class="wow fadeInUp">Contacto</h1>
    </div>
  </div>
      </div>
    </div>
</section>
<!-- ==========FIN MENU=============-->


<!--===============CONTACTO===============-->

<section class="servicios wow fadeInUp">
  <div class="container">
    <div class="row">
       <div class="col-lg-12">
         <h2>Contac<span class="logo-sec">tanos</span></h2>
         <br>
       </div>

             <div class="col-md-5">
               <form name="formwebpcx" action="enviar.php" method="post"> 
                  <div class="form-group has-feedback">
                     <input name="nombre" type="text" class="form-control" placeholder="Nombre" required data-validation-required-message="Porfavor Ingresa Tu Nombre.">
                     <i class="fa fa-user form-control-feedback"></i>
                     <p class="help-block text-danger"></p>
                  </div>

                 <div class="form-group has-feedback">
                     <input name="email" type="email" class="form-control" placeholder="Email" required data-validation-required-messa ge="Porfavor Ingresa Tu Mail">
                     <i class="fa fa-envelope-o form-control-feedback"></i>
                     <p class="help-block text-danger"></p>
                  </div>

                  <div class="form-group has-feedback">
                     <input name="telefono" type="text" onkeypress="return valida(event)" class="form-control" placeholder="Celular" required data-validation-required-message="Porfavor Ingresa Tu Numero Telefonico">
                     <i class="fa fa-mobile form-control-feedback"></i>
                     <p class="help-block text-danger"></p>
                  </div>

                  <div class="form-group has-feedback">
                     <textarea name="mensaje" class="form-control" placeholder="Mensaje..." rows="5"></textarea>
                     <i class="fa fa-commenting-o form-control-feedback"></i>
                  </div>
                  <button type="submit" class="btn btn-primary" value="enviar">Enviar</button>
               </form>
             </div>
            <br>
             <div class="col-md-7">
               <p class="text-justify">Envíanos tu consulta y nos pondremos en contacto contigo lo antes posible, o si lo prefieres ven a visitarnos a nuestra oficina para una atencion personalizada.</p>
              <div class="footer-icon">
               <ul>
                 <li>
                   <span class="fa-stack fa-lg">
                   <i class="fa fa-circle fa-stack-2x"></i>
                   <i class="fa fa-calendar-o fa-stack-1x fa-inverse"></i>
                   </span> Lunes - Viernes, 9am a 7pm
                 </li>

                 <li>
                   <span class="fa-stack fa-lg">
                   <i class="fa fa-circle fa-stack-2x"></i>
                   <i class="fa fa-phone fa-stack-1x fa-inverse"></i>
                   </span>(+56 35)2442827 <a href="tel:+56352442827"><button class="btn-llamar hidden-lg hidden-md">Llamanos</button></a>
                 </li>

                 <li>
                   <span class="fa-stack fa-lg">
                   <i class="fa fa-circle fa-stack-2x"></i>
                   <i class="fa fa-envelope-o fa-stack-1x fa-inverse"></i>
                   </span> info@webpcx.cl
                 </li>

                 <li>
                   <span class="fa-stack fa-lg">
                   <i class="fa fa-circle fa-stack-2x"></i>
                   <i class="fa fa-map-marker fa-stack-1x fa-inverse"></i>
                   </span>Av.Arturo Phillips #325 Santo Domingo.
                 </li>

                 <li>
                   <span class="fa-stack fa-lg">
                   <i class="fa fa-circle fa-stack-2x"></i>
                   <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                   </span><a href="https://www.facebook.com/webpcx">Webpcx Facebook</a>
                 </li>

               </ul>
              </div>
             </div>
                <div class="col-lg-12">
                 <div class="location-info">
                   <iframe src="https://www.google.com/maps/embed?pb=!1m17!1m11!1m3!1d1010.9416030212914!2d-71.61329943348672!3d-33.63389682237947!2m2!1f0!2f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9662382edd7cb735%3A0x36069d7aa684539f!2sWEBPCX+INGENIERIA+LIMITADA!5e1!3m2!1ses!2scl!4v1497283852370" width="100%" height="310px" frameborder="0" class="img-rounded" allowfullscreen></iframe>
                 </div>
     </div>
  </div>
</section>

<!--===============FIN CONTACTO===============-->


<!--===========FOOTER===============-->
<footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-6 col-sm-6 ">
          <div class="wow fadeInDown">
          <div class="footer-icon">
            <img src="{% static 'img/webpcx_png.png' %}" width="250px" class="img-responsive">
          </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-6">
          <div class="wow fadeInDown">
            <div class="footer-icon center-block">
               <ul>
                 <li>
                   <span class="fa-stack fa-lg">
                   <i class="fa fa-circle fa-stack-2x"></i>
                   <i class="fa fa-calendar-o fa-stack-1x fa-inverse"></i>
                   </span> Lunes - Viernes, 9am a 7pm
                 </li>

                 <li>
                   <span class="fa-stack fa-lg">
                   <i class="fa fa-circle fa-stack-2x"></i>
                   <i class="fa fa-phone fa-stack-1x fa-inverse"></i>
                   </span> (+56 35)2442827 <a href="tel:+56352442827"><button class="btn-llamar hidden-lg hidden-md">Llamanos</button></a>
                 </li>
              </ul>
            </div>
          </div>
        </div>
      </div>  
    </div>
</footer>

<div class="footer-abajo">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
               Copyright &copy; Webpcx Ingenieria Ltda 2017.
            </div>
        </div>
    </div>
</div>

<!--===========FIN FOOTER===========-->


<!-- JQUERY -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<!--FIN JQUERY-->

<!-- JAVASCRIPT -->
 <script src="{% static 'js/bootstrap.min.js' %}"></script>
 <script src="{% static 'Morphext-2.4.4/morphext.min.js' %}"></script>
 <script src="{% static 'js/Efectos.js' %}"></script>
 <script src="{% static 'WOW-master/wow.min.js' %}"></script>
<!--FIN JAVASCRIPT -->
 <script>
function valida(e){
    tecla = (document.all) ? e.keyCode : e.which;

    //Tecla de retroceso para borrar, siempre la permite
    if (tecla==8)
    {
        return true;
    }
        
    // Patron de entrada, en este caso solo acepta numeros
    patron =/[0-9]/;
    tecla_final = String.fromCharCode(tecla);
    return patron.test(tecla_final);
}
</script>

<!--SCRIPT CHAT-->
    <script type="text/javascript" async="async" defer="defer" data-cfasync="false" src="https://mylivechat.com/chatinline.aspx?hccid=67705747"></script>
<!--SCRIPT CHAT-->

<!--FIN JAVASCRIPT -->


</body>
</html>

PC/templates/LogSec.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta name="keywords" content="Instalacion de Camaras y Sistemas de seguridad, camara de seguridad, cctv e Ip, kit dvr, servidores, certificacion vms milestone, redes de fibra optica y cobre, soporte tecnico e informatico a empresas"/>
  <meta name="description" content="Empresa especializada en servicios e instalacion de proyectos de seguridad e informatica, como cámaras y sistemas de seguridad con certificacion milestone, kit dvr, servidores, sistemas informáticos e instalaciones de redes fibra optica y cobre" />
  <meta charset="UTF-8">
  <meta name="robots" content="index,follow">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
<!-- Facebook -->
<meta property="og:site_name" content="webpcx.cl">
<meta property="og:type" content="website">
<meta property="og:title" content="Webpcx | Camaras y sistemas de seguridad">
<meta property="og:description" content="Webpcx |Camaras y sistemas de seguridad">
<meta property="og:url" content="http://www.webpcx.cl">
<meta property="og:image" content="http://webpcx.cl/img/empresa-certificada-milestone.png" />
<meta property="og:image:type" content="image/png" />
<meta property="og:image:width" content="300" />
<meta property="og:image:height" content="300" /> 
<!-- /Facebook -->




  <title>Webpcx | Instalacion de camaras y sistemas de seguridad</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'animate-css/animate.min.css' %}">
  <link rel="stylesheet" href="{% static 'Morphext-2.4.4/morphext.css' %}">
  <link rel="stylesheet" href="{% static 'css/webpcx.css' %}">

</head>


<body >
<!-- ==========MENU=================-->
 
    <!--HEADER-->
    <div class="header">
      <div class="fondo-header">
        <header >
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#miNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'Webpcx:index' %}"><span class="logo-prim">Web</span><span class="logo-sec">Pcx</span></a>
            </div>
            <div class="collapse navbar-collapse" id="miNavbar">
              <ul class="nav navbar-nav navbar-right">
                <li class="active"><a href="{% url 'Webpcx:index' %}">Inicio</a></li>
                <li class=""><a href="{% url 'Webpcx:Servicios' %}">Servicios</a></li>
                <li class=""><a href="{% url 'Webpcx:Contacto' %}">Contacto</a></li>
                <li class=""><a href="{% url 'Webpcx:Noticias' %}">Noticias</a></li>
              </ul>
            </div>
          </div>
        </nav>
        </header>

<section id="introServicio">
    <div class="container-intro">
       <div class="responsivo">
           <div class="intro-logo wow fadeInDown">
             <img src="{% static 'img/webpcx_png.png'%}" width="950px" alt="logopcx">
           </div>
      <h1 class="rotador wow fadeInUp">Camaras de seguridad, Sistemas De seguridad, Dvr y Servidores,Soporte Tecnico e Informatico, Instalacion Redes de Fibra Optica y Cobre</h1>
       </div>
    </div>
      </div>
  </div>
</section>
<!-- ==========FIN MENU=============-->

<!--===========CONTENIDO============-->

<section class="servicios wow fadeInUp">
    <div class="container">
      <div class="row">
         <div class="col-lg-12">
           <h2>Log<span class="logo-sec">in</span></h2>
           <br>
         </div>
  
               <div class="col-md-12">
                <form method="GET" class="Logsec" name="Logsec" enctype="multipart/form-data">
                
                <!--Nombre-->
                  <input name="nombre" type="text" id="nombre" class="form-control" placeholder="Nombre.." required data-validation-required-message="Porfavor Ingresa Tu Nombre.">
                  <i class="form-control-feedback"></i>
                  <p class="help-block text-danger"></p>
               
                <!--Contraseña-->
                  <input name="clave" type="text" id="clave" class="form-control" placeholder="Contraseña.." required data-validation-required-message="Porfavor Ingresa Tu Mail">
                  <i class="form-control-feedback"></i>
                  <p class="help-block text-danger"></p>

                <!--Boton de Envio-->
                  <button type="submit" class="btn btn-primary">Entrar</button>
                
                </form>
               </div>
              <br>
    </div>
  </section>
<!--===========FIN CONTENIDO========-->

<!--===========FOOTER===============-->
<footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-6 col-sm-6 ">
          <div class="wow fadeInDown">
          <div class="footer-icon">
            <img src="{% static 'img/webpcx_png.png' %}" width="250px" class="img-responsive">
          </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-6">
          <div class="wow fadeInDown">
            <div class="footer-icon center-block">
               <ul>
                 <li>
                   <span class="fa-stack fa-lg">
                   <i class="fa fa-circle fa-stack-2x"></i>
                   <i class="fa fa-calendar-o fa-stack-1x fa-inverse"></i>
                   </span> Lunes - Viernes, 9am a 7pm
                 </li>

                 <li>
                   <span class="fa-stack fa-lg">
                   <i class="fa fa-circle fa-stack-2x"></i>
                   <i class="fa fa-phone fa-stack-1x fa-inverse"></i>
                   </span> (+56 35)2442827 <a href="tel:+56352442827"><button class="btn-llamar hidden-lg hidden-md">Llamanos</button></a>
                 </li>
              </ul>
            </div>
          </div>
        </div>

      </div>  
    </div>
</footer>

<div class="footer-abajo">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
               Copyright &copy; Webpcx Ingenieria Ltda 2017.
            </div>
        </div>
    </div>
</div>
<!--===========FIN FOOTER===========-->

<!-- JQUERY -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<!--FIN JQUERY-->

<!-- JAVASCRIPT -->
 <script src="{% static 'js/bootstrap.min.js' %}"></script>
 <script src="{% static 'Morphext-2.4.4/morphext.min.js' %}"></script>
 <script src="{% static 'js/Efectos.js' %}"></script>
 <script src="{% static 'WOW-master/wow.min.js' %}"></script>
<!--FIN JAVASCRIPT -->

<!--SCRIPT CHAT-->
<script type="text/javascript" async="async" defer="defer" data-cfasync="false" src="https://mylivechat.com/chatinline.aspx?hccid=67705747"></script>
<!--SCRIPT CHAT-->
</body>
</html>

PC/templates/Noticias.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta name="keywords" content="Instalacion de Camaras y Sistemas de seguridad, camara de seguridad, cctv e Ip, kit dvr, servidores, certificacion vms milestone, redes de fibra optica y cobre, soporte tecnico e informatico a empresas"/>
  <meta name="description" content="Empresa especializada en servicios e instalacion de proyectos de seguridad e informatica, como cámaras y sistemas de seguridad con certificacion milestone, kit dvr, servidores, sistemas informáticos e instalaciones de redes fibra optica y cobre" />
  <meta charset="UTF-8">
  <meta name="robots" content="index,follow">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
<!-- Facebook -->
<meta property="og:site_name" content="webpcx.cl">
<meta property="og:type" content="website">
<meta property="og:title" content="Webpcx | Camaras y sistemas de seguridad">
<meta property="og:description" content="Webpcx |Camaras y sistemas de seguridad">
<meta property="og:url" content="http://www.webpcx.cl">
<meta property="og:image" content="http://webpcx.cl/img/empresa-certificada-milestone.png" />
<meta property="og:image:type" content="image/png" />
<meta property="og:image:width" content="300" />
<meta property="og:image:height" content="300" /> 
<!-- /Facebook -->




  <title>Webpcx | Instalacion de camaras y sistemas de seguridad</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'animate-css/animate.min.css' %}">
  <link rel="stylesheet" href="{% static 'Morphext-2.4.4/morphext.css' %}">
  <link rel="stylesheet" href="{% static 'css/webpcx.css' %}">

</head>


<body >
<!-- ==========MENU=================-->
 
    <!--HEADER-->
    <div class="header">
      <div class="fondo-header">
        <header >
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#miNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'Webpcx:index' %}"><span class="logo-prim">Web</span><span class="logo-sec">Pcx</span></a>
            </div>
            <div class="collapse navbar-collapse" id="miNavbar">
              <ul class="nav navbar-nav navbar-right">
                <li class="active"><a href="{% url 'Webpcx:index' %}">Inicio</a></li>
                <li class=""><a href="{% url 'Webpcx:Servicios' %}">Servicios</a></li>
                <li class=""><a href="{% url 'Webpcx:Contacto' %}">Contacto</a></li>
                <li class=""><a href="{% url 'Webpcx:Noticias' %}">Noticias</a></li>
              </ul>
            </div>
          </div>
        </nav>
        </header>

<section id="introServicio">
    <div class="container-intro">
       <div class="responsivo">
           <div class="intro-logo wow fadeInDown">
             <img src="{% static 'img/webpcx_png.png'%}" width="950px" alt="logopcx">
           </div>
      <h1 class="rotador wow fadeInUp">Camaras de seguridad, Sistemas De seguridad, Dvr y Servidores,Soporte Tecnico e Informatico, Instalacion Redes de Fibra Optica y Cobre</h1>
       </div>
    </div>
      </div>
  </div>
</section>
<!-- ==========FIN MENU=============-->

<!--===========CONTENIDO============-->

<section class="servicios wow fadeInUp">
    <div class="container">
      <div class="row">
         <div class="col-lg-12">
           <h2>Lista d<span class="logo-sec">e Noticias</span></h2>
           <br>
         </div>
  
               <div class="col-md-12">

                {% for Webpcx in list %}
                  <!--
                  {{Webpcx.titulo}} referencia al titulo en la base de datos
                  <br>
                  {{Webpcx.fecha}} referencia a la fecha en la base de datos
                  <br>
                  {{Webpcx.descripcion}} referencia a la descripcion en la base de datos
                  <br>
                  {{Webpcx.link}} referencia al enlace en la base de datos
                  <br>
                  {{Webpcx.imagen}} referencia a la imagen en la base de datos
                  -->
                <h2>
                    <a href="{{Webpcx.link}}" target="_blank">{{Webpcx.titulo}}</a>
                  </h2>
                  <p>{{Webpcx.fecha}}</p>
                  <hr>
                    <img class="img-responsive center-block" src="{{Webpcx.imagen.url}}" alt="">
                  <hr>
                  <p>{{Webpcx.descripcion}}</p>
                  <a class="btn btn-primary" href="{{Webpcx.link}}" target="_blank">Leer Mas....</a>
  
                  <hr>
                  {% endfor %}
               </div>
               <ul class="pager">
                  <li class="previous">
                      <a href="#">&larr; Anterior</a>
                  </li>
                  <li class="new">
                    <a href="{% url 'Webpcx:ingresar' %}">Nueva Noticia</a>
                  </li>
                  <li class="next">
                      <a href="#">Siguiente &rarr;</a>
                  </li>
              </ul>
              <br>
    </div>
  </section>
<!--===========FIN CONTENIDO========-->

<!--===========FOOTER===============-->
<footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-6 col-sm-6 ">
          <div class="wow fadeInDown">
          <div class="footer-icon">
            <img src="{% static 'img/webpcx_png.png' %}" width="250px" class="img-responsive">
          </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-6">
          <div class="wow fadeInDown">
            <div class="footer-icon center-block">
               <ul>
                 <li>
                   <span class="fa-stack fa-lg">
                   <i class="fa fa-circle fa-stack-2x"></i>
                   <i class="fa fa-calendar-o fa-stack-1x fa-inverse"></i>
                   </span> Lunes - Viernes, 9am a 7pm
                 </li>

                 <li>
                   <span class="fa-stack fa-lg">
                   <i class="fa fa-circle fa-stack-2x"></i>
                   <i class="fa fa-phone fa-stack-1x fa-inverse"></i>
                   </span> (+56 35)2442827 <a href="tel:+56352442827"><button class="btn-llamar hidden-lg hidden-md">Llamanos</button></a>
                 </li>
              </ul>
            </div>
          </div>
        </div>

      </div>  
    </div>
</footer>

<div class="footer-abajo">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
               Copyright &copy; Webpcx Ingenieria Ltda 2017.
            </div>
        </div>
    </div>
</div>
<!--===========FIN FOOTER===========-->

<!-- JQUERY -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<!--FIN JQUERY-->

<!-- JAVASCRIPT -->
 <script src="{% static 'js/bootstrap.min.js' %}"></script>
 <script src="{% static 'Morphext-2.4.4/morphext.min.js' %}"></script>
 <script src="{% static 'js/Efectos.js' %}"></script>
 <script src="{% static 'WOW-master/wow.min.js' %}"></script>
<!--FIN JAVASCRIPT -->

<!--SCRIPT CHAT-->
<script type="text/javascript" async="async" defer="defer" data-cfasync="false" src="https://mylivechat.com/chatinline.aspx?hccid=67705747"></script>
<!--SCRIPT CHAT-->
</body>
</html>